apiVersion: v1
kind: Namespace
metadata:
  name: full-app
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: full-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/scubbo/full-app-deployment
    path: .
    targetRevision: HEAD
  destination: 
    name: hostcluster
    namespace: default
---
apiVersion: crossplane-demo.legalzoom.com/v1alpha1
kind: XApplicationVaultBundle
metadata:
  name: application-vault-bundle-for-full-app
spec:
  owner: scubbo
  serviceName: full-app
